### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cataclisma** [sj-data/stable-diffusion-webui-4koma-gif2grid#1]
I installed this plugin today but I can't get it to run.
Neither a 2x2 grid (512x512 Pixels) nor 3x3 grid (768x768 Pixels)
I always receive an Error _IndexError: list index out of range_.

Console Log:
`Traceback (most recent call last):
  File "C:\Users\user\Downloads\SDXL\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\user\Downloads\SDXL\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\user\Downloads\SDXL\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\Downloads\SDXL\sd.webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\Downloads\SDXL\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\Downloads\SDXL\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\user\Downloads\SDXL\sd.webui\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\user\Downloads\SDXL\sd.webui\webui\extensions\stable-diffusion-webui-4koma-gif2grid\scripts\4koma.py", line 184, in make_gif
    frames[0].save(gif_output_path, save_all=True, append_images=frames[1:], duration=duration, loop=0)
IndexError: list index out of range`

Could you please help me / fix this?

**Comment by cataclisma** [comment]
sorry for nothing!
Forgot to split the grid first.
